services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postsdb
    ports:
      - "5432:5432"
    volumes:
      - ../database/postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network: